<?php

//include/function/common.php
define(INCLUDE_FUNCTION_COMMON_IMPUISSANCE,'操作権限がありません');
define(INCLUDE_FUNCTION_COMMON_LONG_SENTENCE_SYSTEM_SITENAME,"楽しく節約--%s、みんなのクーポン生活");
define(INCLUDE_FUNCTION_COMMON_TODAY_TUANGOU_TITLE,"今日のクーポンは：%s");
define(INCLUDE_FUNCTION_COMMON_THINK_INTEREST,"オススメ情報：");
define(INCLUDE_FUNCTION_COMMON_INTEREST_TITLE ,"オススメ！：%s");
define(INCLUDE_FUNCTION_COMMON_PROCEED,'販売中');
define(INCLUDE_FUNCTION_COMMON_SELLOUT,'販売終了');
define(INCLUDE_FUNCTION_COMMON_TUANGOU_FAIL,'クーポン非成立');
define(INCLUDE_FUNCTION_COMMON_TUANGOU_SUCCESS,'クーポン成立');
define(INCLUDE_FUNCTION_COMMON_OVER,'販売終了');
define(INCLUDE_FUNCTION_COMMON_CITY_LIST,'エリアリスト');
define(INCLUDE_FUNCTION_COMMON_TUANGOU_CATEGORY,'クーポンカテゴリ');
define(INCLUDE_FUNCTION_COMMON_BBS_LAYOUT,'クチコミ掲示板');
define(INCLUDE_FUNCTION_COMMON_USER_GRADE,'ユーザークラス');
define(INCLUDE_FUNCTION_COMMON_EXPRESS_COMPANY,'配送業者');
define(INCLUDE_FUNCTION_COMMON_TAGGING,'タギング');

//include/function/current.php
define(INCLUDE_FUNCTION_CURRENT_TODAY_TUANGOU,'本日のクーポン');
define(INCLUDE_FUNCTION_CURRENT_REVIEW_TUANGOU,'過去のクーポン');
define(INCLUDE_FUNCTION_CURRENT_PLAY,'の使い方');
define(INCLUDE_FUNCTION_CURRENT_EMAIL_SUBSCRIBE,'お知らせメール');
define(INCLUDE_FUNCTION_CURRENT_TEST_QUERY_DB,'テストクエリ');
define(INCLUDE_FUNCTION_CURRENT_BBS,'クチコミ掲示板');
define(INCLUDE_FUNCTION_CURRENT_INDEX,'管理画面トップ');
define(INCLUDE_FUNCTION_CURRENT_TUANGOU,'クーポン管理');
define(INCLUDE_FUNCTION_CURRENT_ORDER,'オーダー管理');
define(INCLUDE_FUNCTION_CURRENT_USER,'ユーザー管理');
define(INCLUDE_FUNCTION_CURRENT_SELLER,'店舗管理');
define(INCLUDE_FUNCTION_CURRENT_MARKETING,'メルマガ管理');
define(INCLUDE_FUNCTION_CURRENT_CATEGORY,'カテゴリ管理');
define(INCLUDE_FUNCTION_CURRENT_INSTALL,'詳細設定');
define(INCLUDE_FUNCTION_CURRENT_SELLER_DATA,'店舗データ');
define(INCLUDE_FUNCTION_CURRENT_LIST,'リスト');
define(INCLUDE_FUNCTION_CURRENT_ALL,'全て');
define(INCLUDE_FUNCTION_CURRENT_BBS_NAME,"掲示板＠%s");
define(INCLUDE_FUNCTION_CURRENT_PUBLIC_BBS,'全国掲示板');
define(INCLUDE_FUNCTION_ACCOUNT_SIGNUP,'新規会員登録');
define(INCLUDE_FUNCTION_ACCOUNT_REPASS,'パスワード再発行');
define(INCLUDE_FUNCTION_CURRENT_NOT_USE,'未使用');
define(INCLUDE_FUNCTION_CURRENT_ALREAD_USE,'使用済');
define(INCLUDE_FUNCTION_CURRENT_EXPIRE,'期限切れ');
define(INCLUDE_FUNCTION_CURRENT_MY_ORDER,'マイオーダー');
define(INCLUDE_FUNCTION_CURRENT_MY,'マイ');
define(INCLUDE_FUNCTION_CURRENT_ACCOUNT_BALANCE,'購入履歴');
define(INCLUDE_FUNCTION_CURRENT_ACCOUNT_SET,'アカウント設定');
define(INCLUDE_FUNCTION_CURRENT_ABOUT,'アバウト');
define(INCLUDE_FUNCTION_CURRENT_CONTACT_CONTACT,'お問い合わせ');
define(INCLUDE_FUNCTION_CURRENT_WORK_CHANCE,'会社概要');
define(INCLUDE_FUNCTION_CURRENT_TOKUTEISYOU,'特定商取引法に基づく表記');
define(INCLUDE_FUNCTION_CURRENT_PRIVACY_POLICY,'プライバシーポリシー');
define(INCLUDE_FUNCTION_CURRENT_SERVICE_CLAUSE,'利用規約');
define(INCLUDE_FUNCTION_CURRENT_MEMBER_RULE,'会員規約');
define(INCLUDE_FUNCTION_CURRENT_common_question,'よくある質問');
define(INCLUDE_FUNCTION_CURRENT_WHAT_IS,'とは');
define(INCLUDE_FUNCTION_CURRENT_ALL2,'全て');
define(INCLUDE_FUNCTION_CURRENT_NOT_PAYMENT,'未決済');
define(INCLUDE_FUNCTION_CURRENT_ALREAD_PAYMENT,'決済完了');
define(INCLUDE_FUNCTION_CURRENT_TANGOU_ANSWER,'購入時質問への回答');
define(INCLUDE_FUNCTION_CURRENT_FEEDBACK_IDEA,'クーポンリクエスト');
define(INCLUDE_FUNCTION_CURRENT_INVITATION_RETURN,'紹介ポイント');
define(INCLUDE_FUNCTION_CURRENT_FINANCE_RECORD,'入出金管理');
define(INCLUDE_FUNCTION_CURRENT_UNDERLIEN_CHARGE,'オフライン入金');
define(INCLUDE_FUNCTION_CURRENT_ONLINE_CHARGE,'オンライン入金');
define(INCLUDE_FUNCTION_CURRENT_PAYPAL_RECORD,'Paypal');
define(INCLUDE_FUNCTION_CURRENT_CASH_PAYMENT,'現金');
define(INCLUDE_FUNCTION_CURRENT_REFUND_RECORD,'返金');
define(INCLUDE_FUNCTION_CURRENT_INVITATION_RECORD,'紹介ログ');
define(INCLUDE_FUNCTION_CURRENT_RETURN_RECORD,'ポイント還元');
define(INCLUDE_FUNCTION_CURRENT_NOW_ORDER,'本日のオーダー');
define(INCLUDE_FUNCTION_CURRENT_PAYMENT_ORDER,'決済完了オーダー');
define(INCLUDE_FUNCTION_CURRENT_NOT_PAYMENT_ORDER,'未決済オーダー');
define(INCLUDE_FUNCTION_CURRENT_USER_LIST,'ユーザーリスト');
define(INCLUDE_FUNCTION_CURRENT_ADMIN_LIST,'管理者リスト');
define(INCLUDE_FUNCTION_CURRENT_NOW_TUANGOU,'本日のクーポン');
define(INCLUDE_FUNCTION_CURRENT_SUCCESS_TUANGOU,'成立クーポン');
define(INCLUDE_FUNCTION_CURRENT_FAIL_TUANGOU,'非成立クーポン');
define(INCLUDE_FUNCTION_CURRENT_NEW_TUANGOU,'新規クーポン');
define(INCLUDE_FUNCTION_CURRENT_SYNOPSIS,'概要');
define(INCLUDE_FUNCTION_CURRENT_NOT_CONSUME,'未使用');
define(INCLUDE_FUNCTION_CURRENT_ALREAD_CONSUME,'使用済');
define(INCLUDE_FUNCTION_CURRENT_OVERDUE,'期限切れ');
define(INCLUDE_FUNCTION_CURRENT_VOUCHER,'金券');
define(INCLUDE_FUNCTION_CURRENT_NEW_VOUCHER,'新規金券');
define(INCLUDE_FUNCTION_CURRENT_SELLER_LIST,'店舗リスト');
define(INCLUDE_FUNCTION_CURRENT_NOW_SELLER,'新規店舗');
define(INCLUDE_FUNCTION_CURRENT_MAIL_MARKETING,'メールマーケティング');
define(INCLUDE_FUNCTION_CURRENT_MESSAGE_FANOUT,'SMS発送');
define(INCLUDE_FUNCTION_CURRENT_DATA_DOWNLOAD,'データダウンロード');
define(INCLUDE_FUNCTION_CURRENT_PHONE_NUMBER,'携帯番号');
define(INCLUDE_FUNCTION_CURRENT_EMAIL_ADDR,'メールアドレス');
define(INCLUDE_FUNCTION_CURRENT_TUANGOU_ORDER,'クーポンオーダー');
define(INCLUDE_FUNCTION_CURRENT_TUANGOU_COUPON,'クーポン');
define(INCLUDE_FUNCTION_CURRENT_USER_INFO,'ユーザ情報');
define(INCLUDE_FUNCTION_CURRENT_BASIC,'基本設定');
define(INCLUDE_FUNCTION_CURRENT_BULLETIN,'広告');
define(INCLUDE_FUNCTION_CURRENT_PAYMENT,'支払');
define(INCLUDE_FUNCTION_CURRENT_MAIL,'メール');
define(INCLUDE_FUNCTION_CURRENT_MESSAGE,'SMS');
define(INCLUDE_FUNCTION_CURRENT_CITY,'エリア');
define(INCLUDE_FUNCTION_CURRENT_PAGE,'ページ編集');
define(INCLUDE_FUNCTION_CURRENT_CACHE,'キャッシュ設定');
define(INCLUDE_FUNCTION_CURRENT_SKIN,'スキン');
define(INCLUDE_FUNCTION_CURRENT_TEMPLATE,'テンプレート');
define(INCLUDE_FUNCTION_CURRENT_UPGRADE,'アップグレード');


//include/function/mailer.php
define(INCLUDE_FUNCTION_MAILER_THANKS_REGISTER,'お申込ありがとうございます。');
define(INCLUDE_FUNCTION_MAILER_VERIFICATION_EMAIL,'、登録を完了するために、リンクをクリックしてください。');
define(INCLUDE_FUNCTION_MAILER_RESET_PASSWORD,'パスワードリセット');
define(INCLUDE_FUNCTION_MAILER_SUNDAY,'日曜日');
define(INCLUDE_FUNCTION_MAILER_MONDAY,'月曜日');
define(INCLUDE_FUNCTION_MAILER_TUESDAY,'火曜日');
define(INCLUDE_FUNCTION_MAILER_WEDNESDAY,'水曜日');
define(INCLUDE_FUNCTION_MAILER_THURSDAY,'木曜日');
define(INCLUDE_FUNCTION_MAILER_FRIDAY,'金曜日');
define(INCLUDE_FUNCTION_MAILER_SATURDAY,'土曜日');

define(INCLUDE_FUNCTION_MAILER_YMD,'Y年n月j日 ');
define(INCLUDE_FUNCTION_MAILER_TODAY_GROUP_BUY,"本日のクーポン：%s");


//include/function/sms.php
define(INCLUDE_FUNCTION_SMS_SMS_LENGTH,'SMSは20文字以上を入力してください');
define(INCLUDE_FUNCTION_SMS_INVALID,'メッセージが届きません');
define(INCLUDE_FUNCTION_SMS_SET_PHONE_NUMBER,'SMSを受信するため、携帯電話の番号を正しく設定してください');


//include/function/utility.php
define(INCLUDE_FUNCTION_UTILITY_FROM,'#住所：<b>(.+)</b>#Ui');
define(INCLUDE_FUNCTION_UTILITY_MALE,'男');
define(INCLUDE_FUNCTION_UTILITY_FEMALE,'女');
define(INCLUDE_FUNCTION_UTILITY_PAID,'決済完了');
define(INCLUDE_FUNCTION_UTILITY_UNPAID,'未決済');
define(INCLUDE_FUNCTION_UTILITY_ALIPAY,'支付宝');
define(INCLUDE_FUNCTION_UTILITY_TENPAY,'付通');
define(INCLUDE_FUNCTION_UTILITY_CHINABANK,'中国銀行');
define(INCLUDE_FUNCTION_UTILITY_CASH,'現金');
define(INCLUDE_FUNCTION_UTILITY_CREDIT_CARD,'クレジットカード');
define(INCLUDE_FUNCTION_UTILITY_OTHER,'その他');
define(INCLUDE_FUNCTION_UTILITY_EXPRESS_DELIVERY,'宅配便');
define(INCLUDE_FUNCTION_UTILITY_COUPON,'クーポン');
define(INCLUDE_FUNCTION_UTILITY_SELF_PICK,'店頭引換え');
define(INCLUDE_FUNCTION_UTILITY_BUY,'購入');
define(INCLUDE_FUNCTION_UTILITY_INVITE,'紹介');
define(INCLUDE_FUNCTION_UTILITY_RECHARGE,'チャージ');
define(INCLUDE_FUNCTION_UTILITY_WITHDRAW,'引落し');
define(INCLUDE_FUNCTION_UTILITY_REBATE,'紹介料');
define(INCLUDE_FUNCTION_UTILITY_REFUND,'払い戻し');
define(INCLUDE_FUNCTION_UTILITY_REGISTER,'登録');
define(INCLUDE_FUNCTION_UTILITY_NUMBER_OF_PEOPLE,'目標人数達成により成立');
define(INCLUDE_FUNCTION_UTILITY_QUANTITY,'販売個数達成により成立');

//ajax/topic.php
define(AJAX_TOPIC_TOPIC_NOT_EXIST,'トピックスがありません');
define(AJAX_TOPIC_DELETE_TOPIC_SUCCEED,'トピックスを削除しました');
define(AJAX_TOPIC_ONLY_PRIMARY_TOPIC_CAN_TOP,'メイントピックスはトップ掲載が可能です');
define(AJAX_TOPIC_SET_TOPIC_ISTOP_SUCCEED,'メイントピックスに設定しました');
define(AJAX_TOPIC_CANCLE_TOPIC_ISTOP_SUCCEED,'メイントピックス設定を解除しました');

//ajax/order.php
define(AJAX_ORDER_ORDER_HISTORY_NOT_EXIST,'オーダー履歴がありません');
define(AJAX_ORDER_COUPON_USE_SUCCEED,"クーポン使用登録が完了しました");

//coupon/print.php
define(COUPON_PRINT_SYSTEM_COUPONNAME_NOT_EXIST,"このクーポンがありません");
define(COUPON_PRINT_BILL_SYSTEM_COUPONNAME_NOT_BELONGS_YOU,"このクーポンは使用できません");
//feed.php
define(FEED_GROUP_BUY_TODAY,"{$INI['system']['sitename']}本日のクーポン");
define(FEED_GROUP_BUY_ONCE_A_DAY,"{$INI['system']['sitename']}は一日に1アイテム掲載されます");

//team.php
define(TEAM_WHOLE,'全国');
//unsubscribe.php
define(UNSUBSCRIBE_UNSUBSCRIBE_IS_SUCCESSFUL,'お知らせメール解約後は、毎日クーポンの情報は配信されません');
//upload.php
define(UPLOAD_DOCUMENT_NAME_ERROR,'ファイル名が間違っているか、選択されていません');
define(UPLOAD_UPLOAD_MAX_FILESIZE,'ファイルサイズがPHPサーバーの規定値を超えています');
define(UPLOAD_MAX_FILE_SIZE,'ファイルサイズがシステムの規定値を超えています');
define(UPLOAD_FILE_UPLOAD_INCOMPLETE ,'ファイルアップロードが完了していません');
define(UPLOAD_NO_FILE_UPLOAD ,'ファイルをアップロードしません');
define(UPLOAD_MISSING_A_TEMPORARY_FOLDER ,'一時フォルダが見つかりません');
define(UPLOAD_FAILED_TO_WRITE_FILE ,'ファイルの書き込みに失敗しました');
define(UPLOAD_INTERRUPT ,'アップロードが中断されました');
define(UPLOAD_NO_VALID_ERROR_CODE ,'無効なエラーコード');
define(UPLOAD_FILE_SIZE ,'ファイルサイズを超えています');
define(UPLOAD_BYTE ,'バイト');
define(UPLOAD_UPLOAD_FILE ,'この拡張子のファイルはアップロードできません：');


//account/invite.php
define(ACCUONT_INVITE_INVITED_TO_AWARDS,'お友達紹介キャンペーン');
//account/login.php
define(ACCUONT_LOGIN_LOGIN_FAILED,'ログインに失敗しました');
//account/repass.php
define(ACCUONT_REPASS_EMAIL_NOT_REGISTRATION,'このメールアドレスは登録されていません');
//account/reset.php
define(ACCUONT_RESET_RESET_PASSORD_ERROR,'このリンクは無効です');
define(ACCUONT_RESET_PASSORD_ERROR,'パスワードが一致していません');
//account/settings.php
define(ACCUONT_SETTINGS_SETTINGS_SUCCESS,'アカウント情報を変更しました');
define(ACCUONT_SETTINGS_SETTINGS_FAILED,'アカウント情報を変更できませんでした');
define(ACCUONT_SETTINGS_USERNAME_LENGTH_INVALID,'IDの長さを4-16にしてください');
define(ACCUONT_SETTINGS_REALNAME_LENGTH_INVALID,'名前の長さを2-32にしてください');
define(ACCUONT_SETTINGS_REALNAME_INVALID,'名前の文字が無効です');
define(ACCUONT_SETTINGS_PASSWORDS_DIFFERENT,'パスワード再入力が不同');
define(ACCUONT_SETTINGS_PASSWORD_LENGTH_INVALID,'バスワードの長さを4-16にしてください');
define(ACCUONT_SETTINGS_MOBILE_INVALID,'この電話番号は無効です');
define(ACCUONT_SETTINGS_ZIPCODE_INVALID,'この郵便番号は無効です');
//account/signup.php
define(ACCUONT_SIGNUP_EMAIL_INVALID_ADDRESS,'このメールアドレスは無効です');
define(ACCUONT_SIGNUP_USER_USE,'このニックネームは既に使用されています');
define(ACCUONT_SIGNUP_PASSWORD_ERROR,'このパスワードは使用できません');
define(ACCUONT_SIGNUP_EMAIL_USE,'このメールアドレスは既に使用されています');
define(ACCUONT_SIGNUP_EMAIL_LEN_ERROR,'このメールアドレスは長すぎました');
define(ACCUONT_SIGNUP_PASSWORD_LEN_ERROR,'このパスワードは４～１６文字の以内に入力してください');
define(ACCUONT_SIGNUP_USERNAME_LEN_ERROR,'このニックネームは４～１６文字の以内に入力してください');
define(ACCUONT_SIGNUP_MENBER_CHECK_ERROR,'会員規約とプライバシーポリシーに同意しないと会員を登録できません');
define(ACCUONT_SIGNUP_MOBILE_ERROR,'この電話番号は無効です');
//account/verify.php
define(ACCUONT_VERIFY_EMAIL_VALIDATION_SUCCESS,'ご登録ありがとうございます！お客様のアカウントは利用可能です');

//message/inbox.php

//order/charge.php

define(ORDER_CHARGE_ERROR,'チャージ金額は１円以上です');
define(ORDER_CHARGE_CHG_EMAIL_SYSTEM_SITENAME,"%s(%sチャージ%s円)");

//order/check.php

define(ORDER_CHECK_ERROR, 'オーダーがありません');

//order/index.php

//order/pay.php

define(ORDER_PAY_ERROR, '購入手続きを完了できません');

//order/view.php

//order/alipay/notify.php

define(ORDER_ALIPAY_NOTIFY_BANK, '支付宝');

//order/alipay/return.php

define(ORDER_ALIPAY_RETURN_FEE, "支付宝チャージ%s元が成功！");

define(ORDER_ALIPAY_RETURN_BANK, '支付宝');

//order/chinabank/notify.php

//order/chinabank/return.php

define(ORDER_CHINABANK_RETURN_BANKSUC_AMOUNT,  "オンライン銀行%s元のチャージが成功！");

//order/tenpay/return.php

define(ORDER_TENPAY_RETURN_CAISUC_AMOUNT,  "财付通%s元チャージが成功！");

define(ORDER_TENPAY_RETURN_BANK, '财付通');

//team/ask.php

define(TEAM_ASK_REPLY_SYSTEM_ABBREVIATION_TITLE,"%s回答 %s");

//team/buy.php

define(TEAM_BUY_ERRNOTEXIST, 'クーポンがありません');

define(TEAM_BUY_ERRBUYONE, 'お客様は既にこのクーポンを購入されています');

define(TEAM_BUY_ERRGT, '購入枚数は一枚以上です');

define(TEAM_BUY_ERRRANGE, '購入可能枚数を超えています');

//team/index.php

define(TEAM_INDEX_UPON, '過去のクーポン');
//ajax/coupon.php
define(AJAX_COUPON_INVALIDATE_CID,"#%s&nbsp;無効");
define(AJAX_COUPON_INVALIDATE,'無効');
define(AJAX_COUPON_CONSUME,'使用場所：');
define(AJAX_COUPON_EXPIRED_CID,"#%s&nbsp;期限切れ");
define(AJAX_COUPON_EXPIRATION_DATE,'有効期限（日）：');
define(AJAX_COUPON_VALID_CID,"#%s&nbsp;は有効です");
define(AJAX_COUPON_DATE_EXPIRY_E,"有効期間&nbsp;%s");
define(AJAX_COUPON_CONSUMER_FAILED,'使用できません');
define(AJAX_COUPON_NO_PASSWORD_INCORRECT,'認証キーが間違っています');
define(AJAX_COUPON_EXPIRATION_TIME,'有効期限（時刻）：');
define(AJAX_COUPON_CONSUMED_CID,"#%s&nbsp;は使用済みです");
define(AJAX_COUPON_REBATE_COUPON_CREDIT_YUAN," %sポイント還元");
define(AJAX_COUPON_VALID,'有効');
define(AJAX_COUPON_CONSUMPTION_TIME,'使用時刻：');
define(AJAX_COUPON_CONSUMER_SUCCESS,'使用登録が完了しました');
define(AJAX_COUPON_SMS_SEND_5_TIMES_COUPON,'ショートメッセージではクーポンを5回まで送れます');
define(AJAX_COUPON_ILLEGALLY_DOWNLOADING,'無効なダウンロードです');
define(AJAX_COUPON_SEND_SMS_SUCCESS_CHECK_TIME,'ショートメッセージを送りましたので、ご確認ください');
define(AJAX_COUPON_SEND_SMS_FAILED_ERROR_CODE_CODE,"ショートメッセージの送信に失敗しました。エラーコード：%s");

//ajax/manage.php
define(AJAX_MANAGE_MONEY_BACK_SUCCESS,'払い戻し完了');
define(AJAX_MANAGE_PAYMENT_ORDER_CANNOT_DELETED,'支払いオーダーを削除できません');
define(AJAX_MANAGE_DELETED_ORDER_ORDER_ID_SUCCESS,"オーダー(%s)を削除しました");
define(AJAX_MANAGE_CASH_PAYMENT_SUCCESS_PURCHASING_CUSTOM_USER_EMAIL,"現金支払いは成功しました、購入ユーザー：%s");
define(AJAX_MANAGE_GROUP_PURCHASE_PAYMENT_ORDER_CANNOT_DELETED,'当クーポンに購入記録がある為、削除できません');
define(AJAX_MANAGE_GROUP_PURCHASE_ID_CANNOT_DELETED,'当クーポンには購入記録がありましたが、クーポン %s の削除に成功しました');
define(AJAX_MANAGE_NO_RELATED_CASH_COUPON,'関連する金券はありません');
define(AJAX_MANAGE_CASH_COUPON_USED_CANNOT_DELETED,'金券は使用済みの為、削除できません');
define(AJAX_MANAGE_CASH_COUPON_ID_DELETED_SUCCESS,"金券 %s を削除しました");
define(AJAX_MANAGE_BELOW_THE_LINE_RECHARGE,'オフラインチャージ');
define(AJAX_MANAGE_USER_WITHDRAW_DEPOSIT,'ユーザー口座から引落しました');
define(AJAX_MANAGE_RECHARGE_FAILED,'チャージに失敗しました');
define(AJAX_MANAGE_ALTER_EXPRESSAGE_MESSAGE_SUCCESS,"配送業者への伝言を修正しました");
define(AJAX_MANAGE_ALIPAY,'支付宝');
define(AJAX_MANAGE_TENPAY,'财付通');
define(AJAX_MANAGE_CHINABANK_PAYMENT,'网银在线');
define(AJAX_MANAGE_BALANCE_PAYMENT,'残高から決済します');
define(AJAX_MANAGE_BELOW_THE_LINE_PAY,'オフライン決済');
define(AJAX_MANAGE_GREEN_NON_PAYMENT,'<font color="green">未決済</font>');
define(AJAX_MANAGE_RED_PAID,'<font color="red">決済完了</font>');
define(AJAX_MANAGE_REFUND_ACCOUNT_BALANCE,'アカウントに払い戻します');
define(AJAX_MANAGE_OTHER_WAYS_REFUNDED,'既に返金済みです');
define(AJAX_MANAGE_ILLEGAL_OPERATION,'無効な操作です');
define(AJAX_MANAGE_NOTHING_HAPPENED_PURCHASING_BEHAVIOR_CANNOT_EXECUTE_REBATE,'クーポン未購入の為、ポイント還元ができません');
define(AJAX_MANAGE_SUCCESSFUL_GROUP_PURCHASE_CAN_EXECTUE_INVITE_REBATE,'紹介先がクーポンを購入すると、ポイントが還元されます');
define(AJAX_MANAGE_INVITE_REBATE_SUCCESSFUL_OPERATION,'紹介ポイントを還元しました');
define(AJAX_MANAGE_WRONFUL_INVITE_RECORD_DELETED_SUCCESS,'無効な紹介記録を削除しました');
define(AJAX_MANAGE_EMAIL_EMAIL_UNSUBSCRIPTION_SUCCESS,"メールアドレス：%sお知らせメールを解除しました");
define(AJAX_MANAGE_MERCHANT_ID_DELETE_SUCCEED,'店舗：%s を削除しました');
define(AJAX_MANAGE_MERCHANT_HAVE_GROUP_PURCHASE_ITEM_DELETE_FAILED,'この店舗はクーポンがある為、削除できません');
define(AJAX_MANAGE_DELETE_MERCHANT_FAILED,'店舗を削除できません');
define(AJAX_MANAGE_SENT_SUCCEED,'発送を完了しました');
define(AJAX_MANAGE_SUBSCRIBE_MAIL_SENT_SUCCEED,'お知らせメールを発送しました');
define(AJAX_MANAGE_NO_DATA,'データはありません');
define(AJAX_MANAGE_PLEASE_MAKE_SURE_CATEGORY,'カテゴリを確認してください');
define(AJAX_MANAGE_NO_SUCH_CATEGORY,'このカテゴリがありません');
define(AJAX_MANAGE_GROUP_PURCHASE_ITEM_EXISTS_UNDER_THIS_CATEGORY,'当カテゴリにはクーポンがあります');
define(AJAX_MANAGE_ORDER_ITEM_EXISTS_UNDER_THIS_CATEGORY,'当カテゴリにはオーダーがあります');
define(AJAX_MANAGE_DISCUSSION_TOPIC_EXISTS_UNDER_THIS_CATEGORY,'当カテゴリの掲示板にはトピックスがあります');
define(AJAX_MANAGE_DELETE_CATEGORY_SUCCEED,'カテゴリを削除しました');
define(AJAX_MANAGE_GROUP_PURCHASE_NOT_CLOSED_OR_NOT_MEET_MINIMUM_NUMBER_PEOPLE_INTO_GROUP,'クーポン販売が継続中か、または成立人数に達していません');
define(AJAX_MANAGE_DELIVER_COUPON_SUCCEED,'クーポンを発送しました');

//feedback/seller.php
define(FEEDBACK_SELLER_COMPLETE_FORM_SUBMIT,'提携のお問い合わせを送信しました');

//feedback/suggest.php
define(FEEDBACK_SUGGEST_COMPLETE_FORM_SUBMIT,'クーポンリクエストを送信しました');

//forum/topic.php
define(FORUM_TOPIC_PUBLISH_REPLY_SUCCEED,'返信が完了しました');
define(FORUM_TOPIC_ESPACEFORUM_TITLE,"%s クチコミ掲示板");

//include/classes/ZCard.class.php
define(INCLUDE_CLASSES_ZCARD.CLASS_NOT_EXIST_VOUCHER,'金券がありません');
define(INCLUDE_CLASSES_ZCARD.CLASS_NOT_USES_VOUCHER_BILL,'このクーポンに金券は使えません');
define(INCLUDE_CLASSES_ZCARD.CLASS_VOUCHER_DENOMINATION_RESTRICTED,'金券の金額が足りません');
define(INCLUDE_CLASSES_ZCARD.CLASS_NOTIN_VALIDITY,'有効期間外です');
define(INCLUDE_CLASSES_ZCARD.CLASS_VOUCHER_ALREADY_USED,'この金券は使用済みです');
define(INCLUDE_CLASSES_ZCARD.CLASS_ONEBILL_USES_ONEVOUCHER,'金券は一度に一枚のみ使用できます');
define(INCLUDE_CLASSES_ZCARD.CLASS_UNKNOWN_ERROR,'不明なエラーです');



//include/classes/Zsystem.class.php
define(INCLUDE_CLASSES_ZSYSTEM_CLASS_SITENAME,"UPON");
define(INCLUDE_CLASSES_ZSYSTEM_CLASS_SITETITLE,"UPON");
define(INCLUDE_CLASSES_ZSYSTEM_CLASS_ABBREVIATION,"UPON");
define(INCLUDE_CLASSES_ZSYSTEM_CLASS_COUPONNAME,"UPON");
define(INCLUDE_CLASSES_ZSYSTEM_CLASS_CURRENCY,"¥");


// include/library/AlipayNotify.class.php
define(INCLUDE_LIARBRY_ALIPAYNOTIFY_NOTICE, 'DSA署名方式はまだ開発していません、MD5署名メソッドを使用してください。');
define(INCLUDE_LIARBRY_ALIPAYNOTIFY_NOT_SUPPORT, '支付宝はサポートしていません');
define(INCLUDE_LIARBRY_ALIPAYNOTIFY_SIGNATURE_TYPE, '署名方法の種類');

// include/library/AlipayService.class.php
define(INCLUDE_LIARBRY_ALIPAYNOTIFY_NOTICE, 'DSA DSA署名方式はまだ開発していません、MD5署名メソッドを使用してください。');
define(INCLUDE_LIARBRY_ALIPAYNOTIFY_NOT_SUPPORT, '支付宝はサポートしていません');
define(INCLUDE_LIARBRY_ALIPAYNOTIFY_SIGNATURE_TYPE, '署名方法の種類');

// include/library/Pager.class.php
define(INCLUDE_LIARBRY_PAGER_FIRSTPAGE, '先頭ページ');
define(INCLUDE_LIARBRY_PAGER_LASTPAGE, '前へ');
define(INCLUDE_LIARBRY_PAGER_NEXTPAGE, '次へ');

// include/library/Utility.class.php
define(INCLUDE_LIARBRY_UTILITY_DAYTIME, '%Y-%m-%d 週%a %H:%M');
define(INCLUDE_LIARBRY_UTILITY_DAYS_AGO, '日前');
define(INCLUDE_LIARBRY_UTILITY_HOURS_AGO, '時間前');
define(INCLUDE_LIARBRY_UTILITY_MININUTES_AGO, '分前');
define(INCLUDE_LIARBRY_UTILITY_JUST_NOW, '1分以内');
define(INCLUDE_LIARBRY_UTILITY_SECONDS_AGO, '秒前');
define(INCLUDE_LIARBRY_UTILITY_SUNDAY, '日');
define(INCLUDE_LIARBRY_UTILITY_MONDAY, '月');
define(INCLUDE_LIARBRY_UTILITY_TUESDAY, '火');
define(INCLUDE_LIARBRY_UTILITY_WENSDAY, '水');
define(INCLUDE_LIARBRY_UTILITY_THURSDAY, '木');
define(INCLUDE_LIARBRY_UTILITY_FRIDAY, '金');
define(INCLUDE_LIARBRY_UTILITY_SATURDAY, '土');
define(INCLUDE_LIARBRY_UTILITY_LONGDATE, 'Y年m月d日');
define(INCLUDE_LIARBRY_UTILITY_WEEKDAY, '曜日');